In [2]:
#matrix operation (using vectorization) and transformation using python and SVD using python
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=A+B
D=A-B
E=A*B
F=np.dot(A,B)
A_transpose=A.T
print("Addition:")
print(C)
print("\nSubtraction:")
print(D)
print("\nElement-wise Multiplication:")
print(E)
print("\nMatrix multiplication:")
print(F)
print("\nTranspose:")
print(A_transpose)


Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]

Transpose:
[[1 3]
 [2 4]]


In [4]:
#with svd
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(A)
n_components=2
A_reconstruct=np.dot(U[:, :n_components],np.dot(np.diag(S[:n_components]),VT[:n_components, :]))
print("Orignal Matrix:")
print(A)
print("\nReconstructed Matrix(with reduced dimensions):")
print(A_reconstruct)


Orignal Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
