In [2]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X = iris.data 
y = iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%


In [3]:

import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
iris = datasets.load_iris()
X = iris.data 
y = iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()

nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm=confusion_matrix(y_test,y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(cm)

Accuracy: 100.00%
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [4]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of Naive Bayes: {accuracy:.2f}")
print("\nEnter the flower measurements:")
sepal_length = float(input("Sepal length (cm): "))
sepal_width = float(input("Sepal width (cm): "))
petal_length = float(input("Petal length (cm): "))
petal_width = float(input("Petal width (cm): "))
newrow = np.array([[sepal_length,sepal_width,petal_length,petal_width]])
prediction = nb_classifier.predict(newrow)
species = data.target_names[prediction[0]]
print(f"\nPredicted Iris species: {species}")


Accuracy of Naive Bayes: 1.00

Enter the flower measurements:
Sepal length (cm): 12
Sepal width (cm): 4
Petal length (cm): 5
Petal width (cm): 6

Predicted Iris species: virginica


In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
df = pd.read_csv("/home/ksb/saniya/datascience/fruit.csv")
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
weight=float(input("enter the Fruit weight in grams"))
size=float(input("enter the Fruit size"))
sweetness=float(input("enter the rSweetness score"))
newrow = np.array([[weight,size,sweetness]])
prediction = nb_classifier.predict(newrow)
print("Predicted product :", prediction[0])

enter the Fruit weight in grams134
enter the Fruit size90
enter the rSweetness score87
Predicted product : Banana
